# Default values for incident-bot.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

affinity: {}

args: []

command: []

configMap:
  create: false
  data: {}

database:
  enabled: false
  password:

deploymentAnnotations: {}

envFromSecret:
  enabled: false
  secretName:

envVars:
  CONFIG_FILE_PATH: /config/incident-bot/config.yaml

healthCheck:
  enabled: true
  path: /api/v1/health
  scheme: HTTP
  initialDelaySeconds: 30
  periodSeconds: 30
  timeoutSeconds: 1

image:
  repository: eb129/incident-bot
  pullPolicy: Always
  # suffix:
  # tag:

imagePullSecrets: []

ingress:
  enabled: false
  className: ''
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host:
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: incident-bot-tls
      hosts: []

nodeSelector: {}

podAnnotations: {}

podSecurityContext: {}

replicaCount: 1

resources:
  limits:
    cpu: 500m
    memory: 512M
  requests:
    cpu: 250m
    memory: 128M

securityContext: {}

service:
  type: ClusterIP
  port: 3000

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ''

tolerations: []
