apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    configmap.reloader.stakater.com/reload: incident-bot-config
  labels:
    app: incident-bot
  name: incident-bot
  namespace: incident-bot
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: incident-bot
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations: {}
      creationTimestamp: null
      labels:
        app: incident-bot
    spec:
      containers:
      - args:
        - incidentbot-test.cluster-c6hhonjugo6f.us-east-1.rds.amazonaws.com:5432
        - --
        - python3
        - main.py
        command:
        - ./wait-for-it.sh
        envFrom:
        - secretRef:
            name: incident-bot
        image: payitadmin/incident_bot:v1.13
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /api/v1/health
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 1
        name: incident-bot
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /api/v1/health
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "1"
            memory: 512M
          requests:
            cpu: 250m
            memory: 256M
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /config/incident-bot
          name: incident-bot-config
        - mountPath: /config/google-creds.json
          name: google-creds
          readOnly: true
          subPath: google-creds.json
        - mountPath: /config/jira-api-key
          name: jira-key
          subPath: jira-api-key
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: incident-bot-config
        name: incident-bot-config
      - name: google-creds
        secret:
          defaultMode: 420
          secretName: google-creds
      - name: jira-key
        secret:
          defaultMode: 420
          secretName: jira-key